# Informationen für Entwickler

[NOTE]
====
Die aktuellsten Informationen sind in der englischsprachigen Dokumentation enthalten.

Die in diesem Kapitel zur Verfügung gestellten Informationen werden eventuell in den _MasterSim Developers Guide_ verschoben. 
====

## Erstellen von Bibliotheken und ausführbaren Programmen

### Erstellen mit die Befehlszeile

#### Linux/MacOS

[source,bash]
-----
cd build/cmake
./build.sh
-----

Im Falle fehlender Abhängigkeiten (verlangt zlib) müssen ggfs. die benötigten Entwicklungspakete installiert werden.

#### Windows
Es sind komfortable Skripte für die Erstellung mit Visual Studio 2015 und Qt5 (für die Benutzeroberfläche von _MasterSim_) enthalten. Andere Compiler, wie MinGW, arbeiten genauso gut, die Dateipfade/Suchpfade müssen allerdings manuell konfiguriert werden.

Folgende Dateien sind im `build/cmake`-Verzeichnis:

-----
build\cmake\build_VC.bat <1>
build\cmake\build_VC_x64.bat <2>
-----
<1> for x86 builds
<2> for x64 builds

Damit die Skripte funktionieren, muss Qt am folgenden Ort installiert sein:

-----
c:\Qt\5.11.3\msvc2015 <1>
c:\Qt\5.11.3\msvc2015_64 <2>
-----
<1> für Aufbauten x86 
<2> für Aufbauten x64 

und **jom.exe** findet man unter:

-----
c:\Qt\Tools\QtCreator\bin\jom.exe
-----

`cmake` muss ebenso im Pfad vorhanden sein. Wenn es irgendwo anders installiert ist, können alternativ die Umgebungsvariablen `JOM_PATH` und `CMAKE_PREFIX_PATH` gesetzt werden.
 
Mit dieser Konfiguration können Sie nun entweder im 32-bit- oder 64-bit-Modus weiter bauen:

[source,batch]
-----
cd build\cmake
build_VC14.bat
-----

oder:

[source,batch]
-----
cd build\cmake
build_VC14_x64.bat
-----

Für unterschiedliche Visual-Studio-Versionen oder MinGW kopieren Sie die Batch-Datei und bearbeiten die Pfade in den Batch-Dateien.

### Bibliotheken

Die _MasterSim_-Bibliothek und die Simulationsprojekte hängen von folgenden Bibliotheken ab,  wobei abgesehen von Qt alle im Quelltext-Repository enthalten sind. Somit ist es nicht notwendig, irgendwelche Bibliotheken separat zu installieren:  

**MasterSimulator** und **MasterSimulatorUI**

- IBK-Bibliothek (von IBK, TU Dresden, Germany)
- IBKMK-Bibliothek (von IBK, TU Dresden, Germany), Untergruppe der Mathe-Kernel-Bibliothek der IBK
- TiCPP-Bibliothek (eine angepasste Version, angeboten von IBK, TU Dresden, Germany)
- Minizip and zlib zum Entpacken von FMUs

nur **MasterSimulatorUI**

- https://www.qt.io/developers[Qt 5 Library]
- https://github.com/ghorwin/BlockMod[BlockMod library] (von IBK, TU Dresden, Germany, gehostet auf github)

Die frei verfügbare Version der Bibliotheken (mit Ausnahme von Qt) sind im Unterverzeichnis `third-party` abgelegt.

[WARNING] 
====
Die Bibliotheken im `third-party`  Unterverzeichnis sind möglicherweise veraltet. Nutzen Sie bitte nur den Quelltext im `externals`-Unterverzeichnis des Repositories.
====


## Entwicklungsumgebungen und Projekt-/Sitzungsdateien 

### Qt Creator

Die Entwicklung mit Qt Creator wird unterstützt (und explizit empfohlen) und Projektdateien stehen zur Verfügung. Individuelle Projektdateien befinden sich in Unterverzeichnissen:

    <library/app>/projects/Qt/<library/app>.pro
    
Ausführbare Programme werden abgelegt in: 

    bin/debug        - Ausgabepfad für Entwicklungen mit dem Qt Creator
    bin/release      - standardisierter Ausgabepfad für Erstellung mit cmake

### Visual Studio

#### CMake-erstellte VC-Projektdateien

Die einfachste Variante, die immer funktionieren sollte, ist die CMake-erzeugte VC-Projektdatei und _Solution_ zu verwenden.

Basisschritte: Öffnen Sie ein Konsolenfenster (VC Commandozeilen Fenster) und verwenden Sie dann CMake mit dem Visual Studio Erstellungsdatei-Generator.

Sie können die `build.bat`- oder `built_x64.bat`-Dateien für diesen Zweck wiederverwenden. Öffnen Sie ein Befehlszeilenfenster und wechseln in das Verzeichnis `build/cmake`.

1. Starten Sie entweder `build.bat` oder `build_x64.bat` und drücken Sie Ctrl+C, wenn die Erstellung startet (dann sind alle Umgebungsvariablen und Pfade bereits gesetzt).

2. Verlassen Sie das Unterverzeichnis und erstellen Sie ein neues Unterverzeichnis vc:
+
[source,batch]
-----
> mkdir vc
> cd vc
-----

3. Öffnen Sie `cmake-gui`, geben Sie das Elternverzeichnis als Quellverzeichnis an und wählen Sie einen Visual Studio Generator. 


[source,batch]
-----
> cmake-gui ..
-----

Die so erstellte `*.sln` Datei kann man dann einfach in VC öffnen.

## Weitere Entwickler-Informationen

Alle weiteren Entwicklerinformationen werden der Einfachheit halber nur in der englischen Dokumentation beschrieben.
