# Testreihen und Validierung

Das _MasterSim_ Quelltext-Repository enthält ein Unterverzeichnis `data/tests` mit einem Regressionstest. Diese Testreihe wird genutzt, um zu prüfen, ob alle Algorithmen wie erwartet arbeiten und ob Änderungen am Quelltext versehentlich etwas kaputt machen.

_MasterSim_ durchläuft außerdem die FMU-Quer-Validierung (fmi-cross-check). Die Dateien und Skripte, die mit diesem Test in Verbindung stehen, befinden sich im Unterverzeichnis `cross-check`.


## Regressionstests


### Verzeichnisstruktur

    /data/tests                     - Basisverzeichnis für Tests
    /data/tests/<platform>/<test>   - Basisverzeichnis für eine Testreihe

`platform` ist (gegenwärtig) eine von: `linux64`, `win32`,`win64` und `darwin64`

Jede _Testreihe_ hat eine Reihe von Unterverzeichnissen:

    fmus                 - enthält für den Test benötigte FMU-Archive
    description          - (mathematische) Beschreibung des Test-Problems

Innerhalb der _Testreihe_ können verschiedene ähnliche _Testfälle_ mit modifizierten Parametern oder angepassten Problemlösungs-Szenarien gespeichert sein. _Testfälle_ werden in der Regel als Testreihen gruppiert, wenn sie die gleichen FMUs oder andere Eingangsdateien benutzen. 

Für jeden _Testfall_ existiert eine _MasterSim_-Projektdatei mit der Erweiterung `msim`. Das Skript, welches die Testfälle durchführt, verarbeitet alle `msim`-Dateien, die in der Unterverzeichnisstruktur unter der aktuellen Plattform gefunden werden.

Um die Überprüfung in einem Testfall zu bestehen, muss eine Reihe von Referenzergebnissen vohanden sein, die in einem Unterverzeichnis mit folgendem Namen gespeichert sind: 

    <project_file_without_extension>.<compiler>_<platform>
    
Zum Beispiel:

    FeedthroughTest.gcc_linux
    FeedthroughTest.vc14_win64

Diese Verzeichnisse sind grundsätzlich nach einer durchlaufenen Simulation umbenannte Arbeitsverzeichnisse, in denen alles außer `summary.txt` und `values.csv` beseitigt worden ist.

### Durchlauf der Tests

Die Tests laufen automatisch nach Erstellen der Software ab. Ansonsten kann man die Testreihe auch über ein Skript selbst starten (je nach Plattform):

- `build/cmake/run_tests_win32.bat`
- `build/cmake/run_tests_win64.bat`
- `build/cmake/run_tests.sh`

### Aktualisierung der Referenzergebnisse

Aus einem Testverzeichnis heraus kann man das Script  `update_reference_results.py` aufrufen und dabei die plattformspezifische Verzeichnisendung als Argument angeben.

Beispielsweise würde der Aufruf aus dem Verzeichnis

    data/tests/linux64/Math_003_control_loop

so aussehen:

[source,bash]
-----
> ../../../../scripts/TestSuite/update_reference_results.py gcc_linux
-----

Das Script aktualisiert nun alle Referenzergebnisse in diesem Verzeichnis. Falls die Referenzergebnisse mehrerer Testreihen bearbeitet/aktualisiert werden sollen, so führt man das Skript `update_reference_results_in_subdirs.py` aus einem der oberen Verzeichnisse durch, zum Beispiel von: `data/tests/linux64` (anderen Scriptnamen beachten!):

[source,bash]
-----
> ../../../scripts/TestSuite/update_reference_results_in_subdirs.py gcc_linux
-----


## Regeln für Quervergleiche und die FMI Standard.org Übersicht

Siehe Dokumentation im Unterverzeichnis `cross-check`.

## Verschieden Möglichkeiten, Test-FMUs zu erstellen

### Native C++ FMUs

Ein geeigneter Weg, um eine einfache, sehr spezielle Test-FMU zu erhalten, ist die Verwendung des https://github.com/ghorwin/FMICodeGenerator[FMI Code Generator]-Werkzeugs. Es ist ein Python-Skript mit einer grafischen Benutzeroberfläche, in der FMU-Variablen und -Eigenschaften festgelegt werden können. Mit dieser Information erstellt der Code-Generator ein Quelltextverzeichnis mit einer Programm-Quelltextvorlage und den benötigten Skripten für das Erstellen und Verpacken der FMUs. Damit ist es sehr einfach, eigene FMUs zu erstellen (siehe auch Dokumentation/Tutorial auf der Webseite https://github.com/ghorwin/FMICodeGenerator).

### Modelica-basierte FMUs

#### FMUs aus kommerziellen Modelica-Entwicklungsumgebungen

Benötigt eine entsprechende passende Lizenz. Das Exportieren von FMUs aus SimulationX oder Dymola ist recht einfach, aber für die Windows-Plattform beschränkt.

OpenModelica kann ebenso FMUs exportieren. Nachfolgend sind die Schritte erläutert, um so eine FMU zu erstellen.

### Erstellen einer FMU mit OpenModelica

Zunächst wird ein Modelica-Modell erstellt.

[IMPORTANT]
====
Versehen Sie Variablen, die als Ausgangsgrößen von der FMU bereitgestellt werden sollen, mit dem Stichwort `output`.
====

Zum Beispiel:

[source,c++]
----
model BouncingBall "The 'classic' bouncing ball model"
  type Height=Real(unit="m");
  type Velocity=Real(unit="m/s");
  parameter Real e=0.8 "Coefficient of restitution";
  parameter Height h0=1.0 "Initial height";
  output Height h "Height";
  output Velocity v(start=0.0, fixed=true) "Velocity";
  output Integer bounceCounter(start=0);
  output Boolean falling;
initial equation
  h = h0;
equation
  v = der(h);
  der(v) = -9.81;
  if v < 0 then
    falling = true;
  else
    falling = false;
  end if;
  when h<0 then
    reinit(v, -e*pre(v));
    bounceCounter = pre(bounceCounter) + 1;
  end when;
annotation(
    experiment(StartTime = 0, StopTime = 5, Tolerance = 1e-6, Interval = 0.01));
end BouncingBall;
----


#### Erstellungsvariante 1: Die FMU manuell erstellen

Öffnen Sie zunächst OMShell, tippen Sie dann die folgenden Befehle, um das Modell zu laden und erzeugen Sie eine Co-Simulations-FMU:

[source,bash]
----
>> loadFile("/path/to/modelica/models/BouncingBall/BouncingBall.mo")
>> translateModelFMU(BouncingBall, fmuType="cs")
"/tmp/OpenModelica/BouncingBall.fmu"
----    
    
Die Ausgabe `/tmp/OpenModelica/BouncingBall.fmu` zeigt an, dass die FMU erfolgreich erstellt wurde.

Zur Erstellung von FMUs mit FMI 2.0 Unterstützung:

[source,bash]
----
>> translateModelFMU(BouncingBall, fmuType="cs", version="2.0")
----

#### Erstellungsvariante 2: Skript-basierte automatische FMU-Erzeugung

Erstellen Sie eine Skript-Datei (`createFMU.mos`) mit dem folgenden Inhalt:

[source,c++]
----
loadModel(Modelica, {"3.2.1"}); getErrorString();
loadModel(Modelica_DeviceDrivers); getErrorString();

setLanguageStandard("3.3"); getErrorString();

cd("./fmus");
loadFile("../reference_Modelica/BouncingBall.mo"); getErrorString();

setDebugFlags("backenddaeinfo");getErrorString();
translateModelFMU(BouncingBall, fmuType="cs"); getErrorString();
----

Lassen Sie das Skript laufen, mittels: 

[source,bash]
----
> omc createFMU.mos
----

