= MasterSimulator command line program

The actual simulation is done by the `MasterSimulator` command line program. It basically performs the following steps:

1. It will only read the msim project file (the network representation file is ignord). 
2. Then, a subdirectory for this simulation test case is created (path can be adjusted, see `working-dir` command line options below). 
3. The FMUs are extracted (can be skipped of already extracted, see command line options below)
4. The simulation is run as defined in the project file


.Using MasterSim in a scripted environment
***************
Since the MasterSim project file is plain text and the solver can be started on the command line, it is possible to use MasterSim in a scripted environment and automated processes (e.g. for optimization calculations).
***************


== Command line arguments

General Syntax for the MasterSimulator command line tool:

--------------
Syntax: MasterSimulator [flags] [options] <project file>

Flags:
  --help            Prints the help page.
  --man-page        Prints the man page (source version) to std output.
  --cmd-line        Prints the command line as it was understood by the command
                    line parser.
  --options-left    Prints all options that are unknown to the command line
                    parser.
  -v, --version     Show version info.
  -x, --close-on-exit  Close console window after finishing simulation.
  -t, --test-init   Run the initialization and stop right afterwards.
  --skip-unzip      Do not unzip FMUs and expect them to be unzipped in
                    extraction directories.

Options:
  --verbosity-level=<0..4>
                    Level of output detail (0-4).
  --working-dir=<working-directory>
                    Working directory for master.
--------------

=== Working/output directory

If no working directory is given, the directory path is generated from the project file path with extension removed. For example:

[source,bash]
-------------
/simulations/myScenario.msim

# outputs will be written to
/simulations/myScenario/...
-------------

In the section <<Structure and content of the working directory>> the content of the working directory is explained.

=== Verbosity of console and log file output
MasterSimulator writes progress information/warning and error messages to the console window, and to the file `<working-dir>/logs/screenlog.txt`. The amount of text to be written and the detail level is controlled through the `--verbosity-level` parameter, which determines the amount of debug information generated by the master. 

Verbosity level of 0 disables pretty much all output, verbosity level 1 is the default with normal progress message output. Use higher verbosity levels for debugging purposes or to narrow down the source of an error.
[NOTE]
====
The log file verbosity is always set to 3 during initialization and reset to the default value of 1 or command line value during simulation (to avoid slowdown of the simulation due to excessive output writing).

====

=== Windows specific options

By default, the console window (on Windows) stays open at the end of the simulation unless the `-x` command line flag is passed.

== Structure and content of the working directory

By default, the following directory structure is used. Suppose there is a project file `simProject.msim` describing the simulation scenario using two provided FMUs `part1.fmu` and `part2.fmu` which are referenced inside the project as simulation slaves *P1* and *P2*, respectively. Let's assume these files are located in some subdirectory:

-----
/sim_projects/pro1/simProject.msim
/sim_projects/pro1/fmus/part1.fmu
/sim_projects/pro1/fmus/part2.fmu
-----

When running the master simulator a working directory will be created. By default the file path to this working directory is the project file name without extension.

-----
/sim_projects/pro1/simProject/             - working directory
/sim_projects/pro1/simProject/log/         - log and statistic files
/sim_projects/pro1/simProject/fmus/        - unzipped fmu subdirectories
/sim_projects/pro1/simProject/fmus/part1   - unzipped part1.fmu
/sim_projects/pro1/simProject/fmus/part2   - unzipped part2.fmu
/sim_projects/pro1/simProject/slaves/      - output/working directory for fmu slaves
/sim_projects/pro1/simProject/slaves/P1    - output directory for slave P1
/sim_projects/pro1/simProject/slaves/P2    - output directory for slave P2
/sim_projects/pro1/simProject/results/     - base directory for simulation results
-----

The base directory name, here `simProject` may be changed by using the `--working-directory` command line argument.

=== Directory `fmus`

Inside this directory, the imported FMUs are extracted, each in a subdirectory with basename of the FMU (`part1.fmu` -> `part1`).

When a MasterSim project references several FMUs with same base name, which are for example in different subdirectories, then it will adjust the extraction path name. Example:

[source,python]
------
slave1 : /path/to/fmus/s1.fmu
slave2 : /path/to/fmus/s1.fmu                # <-- second instance of same FMU
slave3 : /path/other/project/fmus/s1.fmu     # <-- different FMU with same basename

# mastersim generates directories
.../fmus/s1
.../fmus/s1_2                                # <-- suffix _2 _3 etc. is added by MasterSim
------

Basically, each 'fmu' file is only extracted once.
[TIP]
====
.Skipping the FMU extraction step
MasterSim provides the command line option `--skip-unzip`, that is very useful for fixing FMUs with errors in the `modelDescription.xml` or missing resources. If such an FMU is encountered, you can ran MasterSimulator once to extract the FMUs into the directory, then edit/adjust the bad files in the respective extraction directory and afterwards run the simulation again with `--skip-unzip`. MasterSim will now directly read the (modified) files and you can save yourself the hassle of zipping and renaming the FMU. Also, you can keep the `modelDescription.xml` opened in the editor and quickly iterate through the edit-and-test-run procedure, until everything works.

See also <<development_help.adoc#_modifyingfixing_fmu_content,Modifying/fixing FMU content>>.
====


=== Directory `slaves`

Often, non-trivial simulation slaves write their own output files, instead of pushing all output data via FMI output variables to the master. In cases, where PDEs are solved and many thousands of variables are generated, this may actually not be possible.

Since a slave FMU may be instantiated several times, hard-coding output paths inside the FMU is generally a bad idea (though still current practice). Also, writing outputs into the current working directory is not too smart either, since the working directory would have to be changed by the master between calls to FMUs, and this is best avoided.

Unfortunately, the FMU standard does not provide the 
The output directory for slaves is only created by slaves who support a parameter that allows specification of such output directory.

