.TH "MASTERSIMULATOR" "1" "January 01, 2022" "0.9.1" "MasterSim"
.SH NAME
MasterSimulator \- FMI Co-Simulation Master
.SH SYNOPSIS
.B MasterSimulator [flags] [options] <project.msim>
.SH DESCRIPTION
.B MasterSimulator
simulates the co-simulation scenario defined in the msim project file. 
By default all temporary files and all output is created in a subdirectory
with the same name as the project. You can change that with the 
.BR --working-dir
option.
.SH FLAGS
.RS
.TP
.B
\fB--help\fP
Prints the help page.
.TP
.B
\fB--cmd-line\fP
Prints the command line as it was understood by the command line parser
.TP
.B
\fB--options-left\fP
Prints all options that are unknown to the command line parser
.TP
.B
\fB-v\fP, \fB--version\fP
Show version info
.TP
.B
\fB-x\fP, \fB--close-on-exit\fP
Close console window after finishing simulation (Windows only)
.TP
.B
\fB-t\fP, \fB--test-init\fP
Run the initialization with all input checks and stop right afterwards
.TP
.B
\fB--skip-unzip\fP
Do not unzip FMUs and expect them to be unzipped in
extraction directories
.RE
.PP
.SH OPTIONS
.RS
.TP
.B
\fB--verbosity-level\fP=<0..3>
Level of output detail (0-3)
.TP
.B
\fB--working-dir\fP=<working-directory>
Specify an alternative working directory for the master, where all output
shall be written into
