.TH "MASTERSIM" 1 "December 31st, 2024" "0.9.8" "MasterSim Manual"
.SH NAME
.B mastersim\fR \- FMI Co-Simulation Master
.SH SYNOPSIS
.B mastersim\fR [flags] [options] <project file>
.SH DESCRIPTION
.B mastersim
simulates the co-simulation scenario defined in the msim project file. By default all temporary and output files are created in a subdirectory with the same name as the project. You can change that with the
.BR --working-dir
option.
.SH FLAGS
.IP "\fB\-\-help\fR" 4
Prints the help page.
.IP "\fB\-\-man-page\fR" 4
Prints the man page (source version) to std output.
.IP "\fB\-\-cmd-line\fR" 4
Prints the command line as it was understood by the command line parser.
.IP "\fB\-\-options-left\fR" 4
Prints all options that are unknown to the command line parser.
.IP "\fB\-v\fR, \fB\-\-version\fR" 4
Show version info.
.IP "\fB\-x\fR, \fB\-\-close-on-exit\fR" 4
Close console window after finishing simulation.
.IP "\fB\-t\fR, \fB\-\-test-init\fR" 4
Run the initialization and stop right afterwards.
.IP "\fB\-\-skip-unzip\fR" 4
Do not unzip FMUs and expect them to be unzipped in extraction directories.

.SH OPTIONS
.IP "\fB\-\-verbosity-level=<0..3>\fR" 4
Level of output detail (0-3).
.IP "\fB\-\-working-dir=<working-directory>\fR" 4
Working directory for master, where FMUs are extracted to and simulation results/log files are written.

