= Developer information

[NOTE]
====
The information provided in this chapter will eventually be moved into the _MasterSim Developers Guide_.
====

== Building the Library and Executables

=== Building on the command line

==== Linux/MacOS

[source,bash]
-----
cd build/cmake
./build.sh [release] [<number of CPUs>]
-----

See `build.sh` for more command options. By default, binaries are build in _release with debug symbols_ mode.

In case of missing dependencies (zlib is required) you may want to install the corresponding development packages.

==== Windows
Convenience scripts are included for building with Visual Studio 2015 and Qt5 (for the user interface of _MasterSim_). Other compilers such as MinGw work as well, but file paths need to be configured manually.

The files are located in the `build/cmake` directory:

-----
build\cmake\build_VC.bat <1>
build\cmake\build_VC_x64.bat <2>
-----
<1> for x86 builds
<2> for x64 builds

For the scripts to work, Qt must be installed in the following location:

-----
C:\Qt\5.15.2\msvc2019 <1>
C:\Qt\5.15.2\msvc2019_64 <2>
-----
<1> for x86 builds
<2> for x64 builds

and **jom.exe** is expected at:

-----
c:\Qt\Tools\QtCreator\bin\jom.exe
-----

Also, `cmake` must be in the path. 

If Qt or JOM is installed elsewhere, the environment variables `JOM_PATH` and `CMAKE_PREFIX_PATH` can be set alternatively (see build-batch files).

With this setup, you can now build either in 32-bit or 64-bit mode:

[source,batch]
-----
cd build\cmake
build_VC.bat
-----

or

[source,batch]
-----
cd build\cmake
build_x64.bat
-----

For different Visual Studio versions or MinGW copy batch file and edit path constants. You may also want to edit these batch files if you have different installation paths.

=== External Libraries

The _MasterSim_ library and the simulator projects depend on the following external/third-party libraries (except for Qt, all are included in the source code repository, so it is not necessary to install these libraries separately):

**MasterSimulator** and **MasterSimulatorUI**

- IBK library (from IBK, TU Dresden, Germany)
- IBKMK library (from IBK, TU Dresden, Germany)
- TiCPP library (adapted version provided by IBK, TU Dresden, Germany)
- minizip and zlib for unzipping FMUs

only **MasterSimulatorUI**

- https://www.qt.io/developers[Qt 5 Library]
- https://github.com/ghorwin/BlockMod[BlockMod library] (from IBK, TU Dresden, Germany, hosted on github)

The release-versions of the libraries (with the exception of Qt) are located in the sub-directory `third-party`.

WARNING: The libraries in the third-party subdir are way outdated. Please only use the source code in the `externals` subdirectory of the repository.



== Development environments and project/session files

=== Qt Creator

Development with Qt Creator is encouraged and project files are provided. Individual project files are in subdirectories 

    <library/app>/projects/Qt/<library/app>.pro
    
Executables are placed in 

    bin/debug        - output path for development with Qt Creator
    bin/release      - default output path for cmake-builds

=== Visual Studio

==== CMake-generated VC project files
The simplest variant that should always work is to use CMake-generated VC project files and solution.

Basic steps: Open a console window, setup VC build environment and all required paths, then use cmake with the Visual Studio makefile generator.

You can re-use the `build.bat` or `build_x64.bat` files for that purpose. Open a command line window and change into the directory `build/cmake`.

. start either  `build.bat` or `build_x64.bat` and press Ctrl+C once building starts.
. leave subdirectory and create a new subdirectory vc:
+
[source,batch]
-----
> mkdir vc
> cd vc
-----

. open cmake gui, given the parent directory as source dir and select a Visual Studio build generator


[source,batch]
-----
> cmake-gui ..
-----

Afterwards you can open the generated `.sln` file and start debugging (development is not really recommended in Visual Studio).

== Helpful stuff related to development on Linux 

Here are some notes collected when I encountered some unexpected difficulties while creating this master simulator:

=== Checking symbols in shared libraries

[source,bash]
----
objdump -t <shared_library>
nm [-CD] <shared library>
----
    
To get all fmi2  functions

[source,bash]
----
objdump -t <shared_library> | grep fmi2
----

== Debugging MasterSim and FMUs

=== Background on shared library handling on Linux

_MasterSimulator_ can be built in Qt Creator in debug mode. By default the qmake projects will create shared libraries for all dependent libraries like IBK, BlockMod, TiCPP etc.

Slaves can also be built to link against their dependency as shared libraries. This happens, for example, when typical IBK-based projects are also built in debug mode. 

Now, since _MasterSim_ and FMU slaves are developed seperately, it is likely that the version of common libraries like IBK, BlockMod, IBKMK etc. differ. This then becomes a problem!

==== Dynamic linking against shared libraries and LD_LIBRARY_PATH

When launching _MasterSimulator_, it will search for dynamic libraries like `libIBK.so` using the environment variable `LD_LIBRARY_PATH`. Also, when the dynamic library of the slave is loaded, again its shared libraries need to be located. Their paths should also be present in `LD_LIBRARY_PATH`. However, if the path now includes two locations, each containing a _different_ version of the `libIBK.so`, the first one found is linked against _both_ _MasterSimulator_ and the slave library. Naturally, this will likely cause undesired behavior and usually result in segfaults.

The same problem may occur even if _MasterSimulator_ is linked statically against its libraries, yet two different FMU slaves are linked dynamically against different versions of the same library (e.g. DELPHIN against IBK 4.9.x and NANDRAD against IBK 5.0.x). Unless the commonly used library uses semantic versioning and stable APIs (for example, library versions with same major and minor version _always_ have identical memory layouts and compilation settings, and thus can be freely exchanged), one has to ensure that only one shared library is in use.

[CAUTION]
====
Rule of thumb: Avoid dynamic linking completely or use dynamic linking only for one library or the master.
==== 

Basically, one needs to ensure that only one set of shared libraries is being used. There are different options, depending on which part of the software you'd like to develop/debug.


### Developing/Debugging MasterSim

When developing MasterSim it is best to compile all FMUs to link statically against their dependencies:

- _MasterSim_ can be developed on Qt Creator in Debug mode and its dependent libraries as shared libs; `LD_LIBRARY_PATH` must hold the location of these libraries
- FMUs are created with CMake either in release, reldeb or debug mode, but statically linked in any case 


### Developing/Debugging FMUs

- _MasterSim_ should be compiled with CMake either in release, reldeb or debug mode, and statically linked against its libraries
- other FMUs should be linked statically
- the FMU to be developed can be opened in Qt Creator and linked dynamically against its dependent libraries; `LD_LIBRARY_PATH` must hold the location of these libraries


=== FMU Debugging Step-by-Step Guide

Assuming you develop the shared FMU library with Qt Creator, you can follow this procedure:

1. build your FMU either in debug mode or release-with-debug-symbols, you can use also an external build tool chain, for example cmake; you can also use an out-of-date version of the FMU library as it will be replaced later anyway
2. compose your FMU and zip it into the fmu archive (you need to do this only once)
3. create your msim test project
4. run _MasterSimulator_ once with the project; it will create the basic directory structure and extract the FMU library into the `project/fmus/xxx/binaries/linux64` directory

5. now create a symlink to the shared library built by Qt Creator that overwrites the .so file there:
+
```
ln -s /path/to/FMU/bin/debug_x64/libFMUSlaveName.so.1.0.0 FMUSlaveName.so
```
+
where `FMUSlaveName.so` is the name of the shared lib inside `binaries/linux64`
6. in Qt Creator, configure the debugging session by specifying _MasterSimulator_ as executable, setting the commandline to contain `/path/to/project.msim --skip-unzip` and set the LD_LIBRARY_PATH environment variable to point to the directory containing any shared libs the FMU links against.
7. Start debugging/FMU development...



== Inside MasterSim

=== Data Types

In simulations with mixed FMUs (v1 and v2) data types should match. Also, the default type-headers are the same for both versions.

Intendet platform for this master is Desktop systems (32bit/64bit), therefore all data types seen by the master algorithms are mapped to:

* `fmi2Boolean` (`bool` in scalar interface functions)
* `int`
* `double`
* `std::string`


=== Connection Graph and Variable Mapping

Variables can be uniquely identified by 

    <slave-name>.<variable-name>
 
and a graph may be defined by:

    A.x1         B.u1
    A.d1         C.du1
    B.x1         C.u1
    B.x2         A.u2
    C.x1         A.u1

First colum are output variables, second column are connected input variables. x are of type real, d of type integer.

Each slave holds for each data type a vector of output values (bool, int, real/double, string).
The master also holds for each data type a vector of connection variables. 

A mapping of variables from local slave storage to global vector and from global vector to input is done with a mapping table for each data type individually: 

**Output mapping - Type Real**


[width="100%",options="header"]
|====================
| Slave | VariableName | global index | local index
|A      | x1       | 0 | 0
|B      | x1       | 1 | 0
|B      | x2       | 2 | 1
|C      | x1       | 3 | 0
|====================

The transfer from local to global data storage is then a simple algorithm:

    loop connectedVariableIndexes:
        copy(localArray[localIndex], globalArray[globalIndex])
        
In case of slave B the array connectedVariableIndexes will be [0, 1].

**Input mapping - Type Real**

For input variables a similar mapping exists. Each slave does not have an input variable cache, instead variables are set individually (see also Newton algorithm and Jacobian generation via DQ algorithm).


[width="100%",options="header"]
|====================
| Slave | VariableName | global index | local value reference
|B      | u1       | 0 | 55
|C      | u1       | 1 | 348432
|A      | u2       | 2 | 122
|A      | u1       | 3 | 321
|====================

Input and output mappings are combined into a single table RealVariableMappings.

**Note**: An output of a slave may be directly connected to any of its own input variables, for example:

    fmu1.var2   fmu1.var15

