= Test Suite Concept

The _MasterSim_ repository includes a subdirectory `data/tests` with a regression test suite. These tests are used to check whether all algorithms work as expected and whether changes in the code base accidentally break something.

_MasterSim_ is also run through the FMI cross-checking tests. The files and scripts related to those tests are in the subdirectory `cross-check`.

== Regression tests

=== Directory structure

    /data/tests                     - root directory for tests
    /data/tests/<platform>/<test>   - base directory for a test suite

`platform` is (currently) one of: `linux64`, `win32`,`win64` and `darwin64`

Each _test suite_ has a set of subdirectories:

    fmus                 - holds fmu archives needed for the test
    description          - (mathematical) description of the test problem

Within a _test suite_ different similar _test cases_ with modified parameters or adjusted solver settings can be stored. _Test cases_ are grouped in test suites mostly when they use the same FMUs or other input files.

For each _test case_ a _MasterSim_ project file exists with the extension `msim`. The script that runs the test cases processes all `msim` files found in the subdirectory structure below the current platform.

For a test case to pass the check, a set of reference results must be present, stored in a subdirectory with name 

    <project_file_without_extension>.<compiler>_<platform>
    
For example:

    FeedthroughTest.gcc_linux
    FeedthroughTest.vc14_win64

These directories are basically renamed working directories after a simulation run, where everything except `summary.txt` and `values.csv` has been removed.

=== Running the tests

The tests are run automatically after building with the build scripts. Otherwise run the appropriate script:

- `build/cmake/run_tests_win32.bat`
- `build/cmake/run_tests_win64.bat`
- `build/cmake/run_tests.sh`

=== Updating reference results

From within a test directory, call the script `update_reference_results.py` with the directory suffix as argument.

For example, from within:

    data/tests/linux64/Math_003_control_loop
    
call:

[source,bash]
-----
> ../../../../scripts/TestSuite/update_reference_results.py gcc_linux
-----

which will update all reference results in this directory. If you want to process/update the reference results of several test suites, execute the following script from one directory up, for example from `data/tests/linux64`:

[source,bash]
-----
> ../../../scripts/TestSuite/update_reference_results_in_subdirs.py gcc_linux
-----

== Cross-Checking Rules and FMI Standard.org Listing

See documentation in subdirectory `cross-check`.

== Ways to generate test FMUs

=== Custom C++ FMUs

A convenient way to get simple, very specific test FMUs is the use of the https://github.com/ghorwin/FMICodeGenerator[FMI Code Generator] tool. Its a python tool with graphical interface where FMU variables and properties can be defined. With that information, the code generator creates a source code directory with template code and related build scripts - such that it is very easy to handcraft own FMUs. See documentation/tutorial on the github page.

=== FMUs exported from SimulationX

Requires a suitable license. Exporting FMUs from SimX is very easy, but limited to the Windows platform.

=== FMUs exported from OpenModelica

OpenModelica can export FMUs as well. Here are the steps to generate such an FMU.

==== Create Modelica Model

Create a modelica model. 
[IMPORTANT]
====
Annotate variables to be used as output quantities with keyword `output`.
====

For example:

[source,c++]
----
model BouncingBall "The 'classic' bouncing ball model"
  type Height=Real(unit="m");
  type Velocity=Real(unit="m/s");
  parameter Real e=0.8 "Coefficient of restitution";
  parameter Height h0=1.0 "Initial height";
  output Height h "Height";
  output Velocity v(start=0.0, fixed=true) "Velocity";
  output Integer bounceCounter(start=0);
  output Boolean falling;
initial equation
  h = h0;
equation
  v = der(h);
  der(v) = -9.81;
  if v < 0 then
    falling = true;
  else
    falling = false;
  end if;
  when h<0 then
    reinit(v, -e*pre(v));
    bounceCounter = pre(bounceCounter) + 1;
  end when;
annotation(
    experiment(StartTime = 0, StopTime = 5, Tolerance = 1e-6, Interval = 0.01));
end BouncingBall;
----


==== Variant 1: Generate FMU manually

First open OMShell, then type the following commands to load the model and generate a co-simulation FMU:

[source,bash]
----
>> loadFile("/path/to/modelica/models/BouncingBall/BouncingBall.mo")
>> translateModelFMU(BouncingBall, fmuType="cs")
"/tmp/OpenModelica/BouncingBall.fmu"
----    
    
The output indicates that the FMU file `/tmp/OpenModelica/BouncingBall.fmu` has been successfully created.

For Version 2.0 of FMI standard use:

[source,bash]
----
>> translateModelFMU(BouncingBall, fmuType="cs", version="2.0")
----

==== Variant 2: Script-based automatic FMU generation

Create a script file (`createFMU.mos`)  with the following content:

[source,c++]
----
loadModel(Modelica, {"3.2.1"}); getErrorString();
loadModel(Modelica_DeviceDrivers); getErrorString();

setLanguageStandard("3.3"); getErrorString();

cd("./fmus");
loadFile("../reference_Modelica/BouncingBall.mo"); getErrorString();

setDebugFlags("backenddaeinfo");getErrorString();
translateModelFMU(BouncingBall, fmuType="cs"); getErrorString();
----

Run the script via:

[source,bash]
----
> omc createFMU.mos
----

---
