# _MasterSimulator_ - Das Befehlszeilen-Programm

Die eigentliche Simulation wird mit dem Befehlszeilen-Programm _MasterSimulator_ durchgeführt. Es führt  grundsätzlich die folgenden Schritte aus:

1. Es liest die msim-Projektdatei (die Netzwerkdarstellung wird ignoriert, da sie nur visuelle Informationen enthält).
2. Danach wird ein Arbeitsverzeichnis für die Simulationsdaten erzeugt (der Pfad kann angepasst werden, siehe: `--working-dir`-Befehlzeilen-Option unten). 
3. Die FUMs werden extrahiert (dies kann übersprungen werden, falls die FMUs bereits entpackt vorliegen, siehe Befehlszeilen-Option `--skip-unzip` unten).
4. Die Simulation wird, wie in der Projekt-Datei konfiguriert, durchgeführt.


.Benutzen von _MasterSim_ in einer geskripteten Umgebung
***************
Da die _MasterSim_-Projekt-Datei einfacher ASCII-Text ist und der Rechenkern durch die Befehlszeile gestartet werden kann, ist es möglich, _MasterSim_ in einer geskripteten Umgebung und in automatisierten Prozessen zu nutzen (z. B. für Optimierungsrechnungen).
***************

[[command_line_arguments]]
## Befehlszeilenargumente

Allgemeine Syntax für das _MasterSimulator_ Kommandozeilenprogramm:

--------------
Syntax: MasterSimulator [Schalter] [Optionen] <Projektdatei>

Schalter:
  --help            Zeigt diese Hilfsseite.
  --man-page        Generiert eine man-Hilfeseite (Quellversion)
  --cmd-line        Zeigt die Befehlszeile, wie sie vom Befehlszeilen-Syntaxanalysierer verstanden wurde.
  --options-left    Zeigt alle Schalter/Optionen, die dem Befehszeilen-Syntaxanalysierer unbekannt sind.
  -v, --version     Zeigt die Versionsinformation.
  -x, --close-on-exit  Schließt das Konsolenfenster nach dem Beenden der Simulation (nur Windows).
  -t, --test-init   Startet die Initialisierung und stoppt sie direkt danach.
  --skip-unzip      Überspringt den Schritt zum Entpacken der FMUs und erwartet bereits entpackte FMU-Archive im Arbeitsverzeichnis.

Optionen:
  --verbosity-level=<0..4>
                    Detailstufe für Programmmeldungen (0-4).
  --working-dir=<working-directory>
                    Arbeitsverzeichnis für den Master.
--------------

[[solver_working_dir]]
### Anpassung des Arbeits- und Ausgangsverzeichnis

Wenn kein Arbeitsverzeichnis vorgegeben wird, wird der Verzeichnis-Pfad zum Arbeitsverzeichs aus dem Pfad zur Projektdatei ohne Dateierweiterung generiert. Zum Beispiel:

[source,bash]
-------------
# Pfad zur Projektdatei
/simulations/myScenario.msim

# Basisverzeichnis für Simulationsdaten und -ergebnisse
/simulations/myScenario/...
-------------

Im Abschnitt <<working_directory_structure>> wird der Inhalt und die Struktur des Arbeitsverzeichnisses erklärt.


### Anpassung der Ausgabedetailstufe

_MasterSimulator_ schreibt Fortschrittsinformationen/Warnungen und Fehlermeldungen in das Konsolenfenster und in die Datei `<working-dir>/logs/screenlog.txt`. Die Menge an geschriebenem Text und die Detailstufe wird durch den `--verbosity-level` Parameter kontrolliert, welcher die Menge der erzeugten Fehler-/Analyseinformationen festlegt.

Bei der Detailstufe 0 (`--verbosity-level=0`) wird so ziemlich je Ausgabe abgeschaltet. Die Detailstufe 1 ist der Standard mit normalen Fortschrittsmeldungen. Nutzen Sie eine höhere Ausgabedetailstufe zur Analyse der integrierten Algorithmen oder zur Eingrenzung von Fehlern.

[NOTE]
====
Die Detailstufe der Protokolldatei ist während der Initialisierungsphase immer auf 3 gesetzt, um möglichst detaillierte FMU-Analyseausgaben in der Protokolldatei zu erhalten. Während der Simulation wird die Ausgabedetailstufe dann auf den Standardwert 1 zurückgesetzt, um eine Verlangsamung der Simulation aufgrund des exzessiven Ausgabeschreibens zu vermeiden. Falls der `--verbosity-level`-Befehlszeilenparameter angegeben ist, wird dieser Wert auch während der Simulation für die Protokolldatei verwendet.
====


### Spezielle Optionen unter Windows

Normalerweise bleibt das Konsolenfenster (bei Windows) am Ende der Simulation offen. Man kann aber durch  Angabe des `-x` Befehlszeilenschalters das Fenster nach Ende der Simulation automatisch schließen lassen.


[[working_directory_structure]]
## Struktur und Inhalt des Arbeitsverzeichnis

_MasterSim_ erstellt eine Verzeichnisstruktur nach folgendem Schema. Angenommen es gibt eine Projekt-Datei `simProject.msim`, welche im Simulationsszenario zwei FMUs `part1.fmu` und `part2.fmu` verwendet. Diese werden innerhalb des Projekts jeweils als Simulations-Slaves *P1* und *P2* bezeichnet. Nehmen wir an, diese Dateien sind in einem Unterverzeichnis abgelegt:

-----
/sim_projects/pro1/simProject.msim
/sim_projects/pro1/fmus/part1.fmu
/sim_projects/pro1/fmus/part2.fmu
-----

Bei Ausführung des Master-Simulators wird ein Arbeitsverzeichnis erstellt. Standardmäßig entspricht der Dateipfad zu diesem Arbeitsverzeichnis dem Projekt-Dateinamen ohne Dateierweiterung.

Die Verzeichnisstruktur sähe dann so aus:

-----
/sim_projects/pro1/simProject/             - Arbeitsverzeichnis
/sim_projects/pro1/simProject/log/         - Logdateien und Statistiken
/sim_projects/pro1/simProject/fmus/        - Entpackte FMUs
/sim_projects/pro1/simProject/fmus/part1   - Entpackte part1.fmu
/sim_projects/pro1/simProject/fmus/part2   - Entpackte part2.fmu
/sim_projects/pro1/simProject/slaves/      - Ausgabe-/Arbeitsverzeichnis für FMU Slaves
/sim_projects/pro1/simProject/slaves/P1    - Ausgabe-/Arbeitsverzeichnis für Slave P1
/sim_projects/pro1/simProject/slaves/P2    - Ausgabe-/Arbeitsverzeichnis für Slave P2
/sim_projects/pro1/simProject/results/     - Ausgabeverzeichnis für Simulationsergebnisse
-----

Der Basisname des Verzeichnisses, hier `simProject`, kann durch Angabe das Befehlszeilenarguments `--working-directory` verändert werden.


### Verzeichnis `log`

Dieses Verzeichnis beinhaltet 3 Dateien:
[horizontal]
`progress.txt`:: beinhaltet den Simulations-Fortschritt (siehe Formatbeschreibung unten)
`screenlog.txt`:: beinhaltet die Konsolenausgabe von _MasterSim_, welche in das Konsolenfenster mit der jeweils angeforderten Detailstufe geschrieben wurde (während der Initialisierung wird immer eine detaillierte Ausgabe an die Log-Datei geschrieben, selbst wenn die Bildschirmausgabe mit `--verbosity-level=0` deaktiviert wurde)
`summary.txt`:: nachdem die Simulation _erfolgreich_ vollendet ist, beinhaltet diese Datei eine Zusammenfassung der relevanten Lösungs- und Algorithmusstatistiken.

Das Format der Datei `progress.txt` ist recht simpel:

----
   Simtime [s] 	   Realtime [s]	 Percentage [%]
            600	       0.000205	         0.0019
           1200	        0.00023	         0.0038
           1800	       0.000251	         0.0057
           2400	       0.000271	         0.0076
            ...             ...             ...
----

Die Datei besitzt 3 Spalten, getrennt durch ein Tabulatorzeichen. Die Datei wird bei laufender Simulation geschrieben und aktualisiert und kann von anderen Werkzeugen genutzt werden, um den Gesamtfortschritt aufzugreifen und Fortschrittsdiagramme zu erzeugen. (Geschwindigkeit/Prozentsatz etc.)

Die Bedeutung der verschiedenen Werte im `summary.txt` werden im Abschnitt <<summary_txt_file>> erklärt.


### Verzeichnis `fmus`

Innerhalb dieses Verzeichnis werden die importierten FMUs extrahiert, jedes in ein Unterverzeichnis mit dem Basisdatei der FMU (`part1.fmu` -> `part1`).

Wenn ein _MasterSim_-Projekt auf verschiedene FMUs desselben Basisnamen Bezug nimmt, welche zum Beispiel in verschiedenen Unterverzeichnissen stehen, wird es den Pfadnamen anpassen. Beispiel: 

[source,python]
------
slave1 : /path/to/fmus/s1.fmu
slave2 : /path/to/fmus/s1.fmu                # <1>
slave3 : /path/other/project/fmus/s1.fmu     # <2>

# von _MasterSim_ erzeugte Verzeichnisse
.../fmus/s1
.../fmus/s1_2                                # <3> 
------
<1> zweite Instanz der gleichen FMU (wird nur einmal entpackt)
<2> andere FMU mit gleichem Basisnamen
<3> Suffix `_2` (bzw. `_3` etc.) wird durch _MasterSim_ angehängt

Grundsätzlich wird jede FMU-Datei nur einmal entpackt.

[TIP]
====
.Überspringen des FMU-Extraktions-Schritts
_MasterSim_ unterstützt die Befehlszeilen-Option `--skip-unzip`, welche sehr nützlich ist, um FMUs durch Korrektur einer fehlerhaften `modelDescription.xml`-Datei oder fehlender Ressourcen zu reparieren. Wenn solch eine FMU auftaucht, können Sie _MasterSimulater_ einmal durchlaufen lassen, um die FMUs in die Verzeichnisse zu extrahieren. Dann kann man die fehlerhaften Dateien im jeweiligen Entpack-Verzeichnis überarbeiten/anpassen und danach die Simulation noch einmal mit `--skip-unzip` durchlaufen lassen. _MasterSim_ wird nun die (veränderten) Dateien direkt lesen und Sie können sich selbst die Mühe des Komprimierens und Umbenennens der FMUs sparen. Ebenso können Sie die `modelDescription.xml` im Editor geöffnet lassen und die wiederholte "Bearbeiten-und-Testsimulieren"-Prozedur schnell durchlaufen, bis alles funktioniert.

Siehe auch Erläuterungen im Abschnitt <<skip_FMU_extraction>>.
====


[[dir_slaves]]
### Verzeichnis `Slaves`

Oft schreiben nicht-triviale Simulations-Slaves ihre eigenen Ausgabedateien, anstatt die gesamten Ausgabedaten per FMU-Ausgabevariablen zum Master zu verschieben. Bei FMUs, in denen partielle Differentialgleichungen gelöst werden, und Feldausgaben mit mehreren tausenden Datenpunkten je Zeitschritt erzeugt werden, wäre dies auch nicht sinnvoll (oder effizient). Für das Schreiben derartiger Ausgaben bräuchte die FMU einen Zielpfad, in den die FMU schreiben darf.

Da eine FMU mehrere Male instanziiert werden kann (d.h. mehrere Slaves werden aus der gleichen FMU-Datei erzeugt), ist die feste Programmierung eines Ausgabepfads innerhalb der FMU im Allgemeinen keine gute Idee (obgleich gegenwärtig noch immer häufige Praxis). Die Ausgaben der unterschiedlichen Slaves würden sich sonst gegenseitig überschreiben.

Ausgaben ins gegenwärtige Arbeitsverzeichnis zu schreiben ist ebenso ungeschickt, da das Arbeitsverzeichnis zwischen den Aufrufen der FMUs eventuell durch den Master geändert werden muss. Dadurch sollte der Zugriff auf das Arbeitsverzeichnis am besten vermieden werden.

Leider unterstützt der FMU-Standard keine Option, einem Slave ein gültiges Ergebnis-/Arbeitsverzeichnis zu übergeben. _MasterSim_ behebt das Problem, indem es Slave-spezifische Verzeichnispfade in einem Parameter, genannt `ResultsRootDir`, angibt. Dazu braucht die FMU lediglich diesen Zeichenketten-Parameter zu deklarieren. Man kann in _MasterSim_ den Wert dieses Parameters natürlich wie bei allen anderen Parametern manuell festlegen.
Wenn allerdings kein Wert in der Projekt-Datei für diesen Parameter festgelegt ist, wird _MasterSim_ den für den Slave erzeugten Pfad im Arbeitsverzeichnis eintragen. Die FMU kann den von _MasterSim_ erzeugten Slave-spezifischen Pfad nutzen und Ausgaben oder andere Daten dort hinein schreiben.

[TIP]
====
Das Analysetool _PostProc_ wird bei Angabe des Projektbasisverzeichnis auch die Ausgaben in den Slave-Verzeichnissen finden und zur Analyse anzeigen.
====

## Return-Code des _MasterSimulator_ -Programms

_MasterSimulator_ gibt folgende Return-Code zurück:

[horizontal]
0:: bei Erfolg
1:: wenn ein Fehler aufgetreten ist (alle Ursachen, von schlechten oder fehlenden FMUs, oder Fehlern während der Berechnung,...), die Datei  `screenlog.txt` beinhaltet Details.

[[simulation_outputs]]
## Simulationsausgaben

### Slave-Ausgabewerte

_MasterSim_ erstellt zwei Ergebnisdateien innerhalb des `results`-Unterverzeichnis:

[horizontal]
`values.csv`:: Ausgabe aller Ausgabevariablen vom Typ Zahl (einschließlich Booleans) von allen Slaves (egal, ob sie verbunden sind oder nicht).
`strings.csv`:: Werte aller Ausgabevariablen vom Typ Zeichenketter aller Slaves.

Abhängig davon, ob _synonyme Variablen_ in der ModelDescription (siehe unten) definiert sind, die Datei `synonymous_variables.txt`.

Zeichenketten-Ausgabe-Dateien werden nur erzeugt, wenn tatsächlich Ausgaben dieses Datentyps von Slaves erzeugt werden. 

### Dateiformat der Ergebnisdateien

Die Ergebnisdateien haben die Erweiterung `csv`, nutzen aber Tabulatorzeichen als Trennzeichen. In der ersten Spalte steht immer der Zeitpunkt. Im Spaltenkopf jeder Spalte kann in [] die Zeiteinheit angegeben werden.

Beispiel `values.csv`-Datei:

----
Time [s] 	slave1.h [-] 	slave1.v [-]
0	1	0
0.001	0.999995099905	-0.0098100000000001
0.0019999999999999	0.99998038981	-0.019619999999999
0.0030000000000001	0.999955869715	-0.029430000000002
0.0040000000000002	0.99992153962	-0.039240000000001
----

Das Dateiformat entspricht dem der csv-Dateien, die als Datei-Lese-Slaves genutzt werden, siehe Abschnitt <<csv_filereader_slaves>>, mit:

- durch Tabulatoren getrennte Spalten,
- Nummern sind im englischen Nummernformat geschrieben, und 
- eine einzelne Überschrift bestimmt die Variablen.

Den FMI- Variablennamen sind die entsprechenden Slave-Namen vorangestellt. Die Einheiten sind in Klammern angegeben und für einheitslose ganzzahlige und boolesche Datentypen, wird die Einheit [-] genutzt. 

[NOTE]
====
Vektorwertige Variablen, z.B. mit Namen "var[12]" werden immer einheitenlos geschrieben, sodass das _PostProc_ Programm erkennt, dass es sich bei [12] nicht um eine Einheit handelt.
====

#### Synonyme Variablen

Einige  FMUs, z.B. solche, die von Modelica Modellen erstellt wurden, können verschiedene (interne) Variblen aufweisen, welche den selben Wert referenzieren. Das passiert, wenn die symbolische Analyse des Modelica Modells diese Variablen als die selben erkennen konnte, z.B. bei einer Gleichung "a = b", wird eine FMU sicher intern nur eine Variable halten, aber gegebenenfalls bei Variablen getrennt als Ausgaben anbieten. Beide Variablen hätten in der `modelDescription.xml`-Datei die gleiche `valueReference` (Wertereferenz).

In diesem Fall schreibt _MasterSim_ die Ausgabevariablen nicht doppelt (dies wäre eine Verschwendung von Festplattenkapazitäten und Simulationszeit, siehe Ticket #47), sondern erstellt eine Datei `synonymous_variables.txt` mit einer Tabelle synonymer Variablen.

Die Tabelle wird als einfache Textdatei geschrieben mit durch Tabulatoren getrennte Spalten:

1. FMU-Dateiname (gegenwärtig wird nur der Dateiname geschrieben - im Fall, dass der _gleiche Dateiname_ mit _unterschiedlichen Dateipfaden_ genutzt wird, muss dies geändert werden)
2. der Name der Variablen, erscheint in der `values.csv`-Datei
3. die synonyme Variable, die nicht in die Ausgabedatei geschrieben wird, da sie ohnehin den gleichen Wert hat.

Ein Beispiel für eine `synonymous_variables.txt`-Datei:

----
ControlledTemperature.fmu	heatCapacitor.T	heatCapacitor.port.T
ControlledTemperature.fmu	heatCapacitor.T	heatingResistor.T_heatPort
ControlledTemperature.fmu	heatCapacitor.T	heatingResistor.heatPort.T
ControlledTemperature.fmu	heatCapacitor.T	temperatureSensor.port.T
ControlledTemperature.fmu	heatCapacitor.T	thermalConductor.port_a.T
ControlledTemperature.fmu	heatingResistor.p.v	heatingResistor.v
ControlledTemperature.fmu	heatingResistor.p.v	idealSwitch.n.v
ControlledTemperature.fmu	constantVoltage.i	constantVoltage.n.i
ControlledTemperature.fmu	constantVoltage.i	constantVoltage.p.i
ControlledTemperature.fmu	constantVoltage.i	heatingResistor.i
ControlledTemperature.fmu	constantVoltage.i	heatingResistor.n.i
ControlledTemperature.fmu	constantVoltage.i	heatingResistor.p.i
ControlledTemperature.fmu	constantVoltage.i	idealSwitch.i
ControlledTemperature.fmu	constantVoltage.i	idealSwitch.n.i
ControlledTemperature.fmu	constantVoltage.i	idealSwitch.p.i
ControlledTemperature.fmu	heatingResistor.LossPower	heatingResistor.heatPort.Q_flow
ControlledTemperature.fmu	fixedTemperature.port.Q_flow	thermalConductor.Q_flow
ControlledTemperature.fmu	fixedTemperature.port.Q_flow	thermalConductor.port_a.Q_flow
ControlledTemperature.fmu	fixedTemperature.port.Q_flow	thermalConductor.port_b.Q_flow
ControlledTemperature.fmu	onOffController.reference	ramp.y
ControlledTemperature.fmu	onOffController.u	temperatureSensor.T
ControlledTemperature.fmu	idealSwitch.control	logicalNot.y
ControlledTemperature.fmu	logicalNot.u	onOffController.y
----

Aus dieser Datei wird ersichtlich, dass die Variablen `heatCapacitor.T`, `heatCapacitor.port.T`, `heatingResistor.T_heatPort`, `heatingResistor.heatPort.T`, `temperatureSensor.port.T` und `thermalConductor.port_a.T` alle den gleichen Wert haben und damit die Variablennamen Synonyme sind.

[[summary_txt_file]]
### Simulations-Statistik/Zusammenfassung

_MasterSim_ beinhaltet eine interne Zeitmessfunktion, welche die Ausführungszeiten der verschiedenen Teile der Software überwachen. Ebenso werden Ausführungshäufigkeiten für verschiedene wichtige Funktionen gezeigt. 
Die Statistik wird ins Konsolenfenster (bei `verbosity-level` > 0) und in die Log-Datei `screenlog.txt`  geschrieben. Dabei wird folgendes Format verwendet (die unteren Zeilen beginnend ab "Part1" sind projektspezifisch).

------
Solver statistics
------------------------------------------------------------------------------
Wall clock time                            =   78.044 ms  
------------------------------------------------------------------------------
Output writing                             =   76.767 ms  
Master-Algorithm                           =    0.666 ms         324
Convergence failures                       =                      41
Convergence iteration limit exceeded       =                      41
Error test time and failure count          =    0.214 ms          85
------------------------------------------------------------------------------
Part1                               doStep =    0.101 ms        1229
                                  getState =    0.070 ms        1116
                                  setState =    0.020 ms         509
Part2                               doStep =    0.079 ms        1496
                                  getState =    0.039 ms        1116
                                  setState =    0.024 ms         776
Part3                               doStep =    0.071 ms        1496
                                  getState =    0.038 ms        1116
                                  setState =    0.040 ms         776
------------------------------------------------------------------------------
------

Die selben Statistikdaten werden in die `summary.txt`-Logsdatei kopiert, dabei aber in ein eher _maschinenfreundliches_ Format (mit Zeitangaben immer in *Sekunden* bzw. der jeweils verwendeten Master-Zeiteinheit):

------
WallClockTime=0.078044
FrameworkTimeWriteOutputs=0.076767
MasterAlgorithmSteps=324
MasterAlgorithmTime=0.000666
ConvergenceFails=41
ConvergenceIterLimitExceeded=41
ErrorTestFails=85
ErrorTestTime=0.000214
Slave[1]Time=0.000191
Slave[2]Time=0.000142
Slave[3]Time=0.000149
------

Die Werte bedeuten im Einzelnen:

Wall clock time (`WallClockTime`):: gesamte Simulationszeit, die nach Abschluss der Initialisierung benötigt wurde. Die Dauer für Entpacken und Laden der Laufzeitbibliotheken wird nicht einbezogen 

Output writing (`FrameworkTimeWriteOutputs`):: Zeit, die für das Schreiben von Ausgabedateien und das Berechnen damit zusammenhängender Werte gebraucht wurde. 

Master-Algorithm:: Zeit, die für den eigentlichen Master-Algorithmus (`MasterAlgorithmTime`) und die Anzahl der Aufrufe des Algorithmus und die gesamten genutzten Zeitschritte aufgewendet wurde (`MasterAlgorithmSteps`). 

Convergence failures (`ConvergenceFails`):: Anzahl der Konvergenzfehler bei iterativen Master-Algorithmen.

Convergence iteration limit exceeded (`ConvergenceIterLimitExceeded`):: Anzahl der Überschreitungen der maximalen Iterationszahl in iterierenden Master-Algorithmen (diese Zahl sollte kleiner oder gleich der Anzahl der Konvergenzfehler sein).

Error test time and failure count:: Anzahl der Fehlertest-Überschreitungen (`ErrorTestFails`) und die insgesamt genutzte Zeit, um die Fehlertests durchzuführen (`ErrorTestTime`). Dies schließt die Zeit ein, die für das Speichern und Zurücksetzen des FMU-Zustands und für die zusätzlichen Kommunikationsschritte benötigt wurde. Dies gilt nur für Master-Algorithmen mit aktivierter Fehlerkontrolle (Richardson-Varianten).

Die übrigen Zeilen zeigen Dauer und Aufrufhäufigkeiten individuell für jeden Slave. Die Zeilen zeigen die genutzte Zeit in den Funktionsaufrufen `doStep()`, `getState()` und `setState()` und die jeweilige Häufigkeit des Aufrufs. Die den Zustand betreffenden Funktionen (state) werden nur für iterierende Master-Algorithmen genutzt, falls die FMUs diese FMI 2 Funktionalität unterstützt. Es ist zu beachten, dass diese Funktionen sowohl vom Master-Algorithmus als auch vom Fehlertest aufgerufen werden (wenn eingeschaltet).

Das Schreiben von Ausgaben (*Output writing*) und Ausführen des Master-Algorithmus (*Master-Algorithm*) sind die beiden Hauptkomponenten des _MasterSimulator_-Pogramms, sodass ihre addierten Zeiten nahe der Gesamtlaufzeit liegen sollten.

Die dritte Spalte in der Konsolen-Ausgabe-Statistik beinhaltet Zähler. Der Zähler für den Master-Algorithmus ist die Gesamtzahl der Ausführungen des Master-Algorithmus, also die Gesamtschrittzahl bzw. Gesamtzahl an _erfolgreich_ absolvierten Kommunikationsintervallen. Neuversuche und Wiederholungen _innerhalb_ des Master-Algorithmus werden hier nicht beachtet.

[TIP]
====
Sie sollten diese Profilierungswerte nutzen, um die Simulation abzustimmen und, im Fall einer sehr langsamen Simulation, herauszufinden, welche FMU die meiste Zeit benötigt. Diese kann man dann gezielt optimieren. Ebenso helfen sie zu erkennen, ob eine der eigentlich schnellen Funktionen, wie die zum Lesen und Rücksetzen des FMU-Zustands, ungewöhnlich lange braucht (beispielsweise, wenn FMU-Intern übermäßig lange Zeit für die  Neuinitialisierung benötigt wird).
====
