= _MasterSimulator_ - the command line program

The actual simulation is done by the `MasterSimulator` command line program. It basically performs the following steps:

1. Read the msim project file (the network representation file is ignored, since it only contains visual information). 
2. Then, a working directory for this simulation test case is created (path can be adjusted, see `--working-dir` command line option below). 
3. The FMUs are extracted (can be skipped if already extracted, see command line option `--skip-unzip` below)
4. The simulation is run as defined in the project file


.Using _MasterSim_ in a scripted environment
***************
Since the _MasterSim_ project file is plain text and the solver can be started on the command line, it is possible to use _MasterSim_ in a scripted environment and automated processes (e.g. for optimization calculations).
***************


== Command line arguments

General Syntax for the MasterSimulator command line tool:

--------------
Syntax: MasterSimulator [flags] [options] <project file>

Flags:
  --help            Prints the help page.
  --man-page        Prints the man page (source version) to std output.
  --cmd-line        Prints the command line as it was understood by the command
                    line parser.
  --options-left    Prints all options that are unknown to the command line
                    parser.
  -v, --version     Show version info.
  -x, --close-on-exit  Close console window after finishing simulation.
  -t, --test-init   Run the initialization and stop right afterwards.
  --skip-unzip      Do not unzip FMUs and expect them to be unzipped in
                    extraction directories.

Options:
  --verbosity-level=<0..4>
                    Level of output detail (0-4).
  --working-dir=<working-directory>
                    Working directory for master.
--------------

=== Working/output directory

If no working directory is given, the directory path is generated from the project file path with extension removed. For example:

[source,bash]
-------------
# path to project file
/simulations/myScenario.msim

# outputs will be written to
/simulations/myScenario/...
-------------

In the section <<_structure_and_content_of_the_working_directory,Structure and content of the working directory>> the content of the working directory is explained.

=== Verbosity of console and log file output
MasterSimulator writes progress information/warning and error messages to the console window, and to the file `<working-dir>/logs/screenlog.txt`. The amount of text to be written and the detail level is controlled through the `--verbosity-level` parameter, which determines the amount of debug information generated by the master. 

Verbosity level of 0 disables pretty much all output, verbosity level 1 is the default with normal progress message output. Use higher verbosity levels for debugging purposes or to narrow down the source of an error.
[NOTE]
====
The log file verbosity is always set to 3 during initialization and reset to the default value of 1 or command line value during simulation (to avoid slowdown of the simulation due to excessive output writing).

====

=== Windows specific options

By default, the console window (on Windows) stays open at the end of the simulation unless the `-x` command line flag is passed.

== Structure and content of the working directory

By default, the following directory structure is used. Suppose there is a project file `simProject.msim` describing the simulation scenario using two provided FMUs `part1.fmu` and `part2.fmu` which are referenced inside the project as simulation slaves *P1* and *P2*, respectively. Let's assume these files are located in some subdirectory:

-----
/sim_projects/pro1/simProject.msim
/sim_projects/pro1/fmus/part1.fmu
/sim_projects/pro1/fmus/part2.fmu
-----

When running the master simulator a working directory will be created. By default the file path to this working directory is the project file name without extension.

-----
/sim_projects/pro1/simProject/             - working directory
/sim_projects/pro1/simProject/log/         - log and statistic files
/sim_projects/pro1/simProject/fmus/        - unzipped fmu subdirectories
/sim_projects/pro1/simProject/fmus/part1   - unzipped part1.fmu
/sim_projects/pro1/simProject/fmus/part2   - unzipped part2.fmu
/sim_projects/pro1/simProject/slaves/      - output/working directory for fmu slaves
/sim_projects/pro1/simProject/slaves/P1    - output directory for slave P1
/sim_projects/pro1/simProject/slaves/P2    - output directory for slave P2
/sim_projects/pro1/simProject/results/     - base directory for simulation results
-----

The base directory name, here `simProject` may be changed by using the `--working-directory` command line argument.

=== Directory `log`

This directory contains three files:

`progress.txt`:: contains overall simulation progress
`screenlog.txt`:: contains the output of _MasterSim_ written to the console window with the requested verbosity level (during initialization, always detailed output is written to the logfile, even if nothing is written on the screen due to low verbosity level)
`summary.txt`:: after the simulation has completed _successfully_, this file contains a summary of the relevant solver/algorithm statistics.

The format of the `progress.txt` is fairly simple:

----
   Simtime [s] 	   Realtime [s]	 Percentage [%]
            600	       0.000205	         0.0019
           1200	        0.00023	         0.0038
           1800	       0.000251	         0.0057
           2400	       0.000271	         0.0076
            ...             ...             ...
----

The file has three columns, separated by a Tab character. The file is written and updated during the simulation run and can be used by other tools to pick up the overall progress and generate progress diagrams (speed/percentage etc.)

The meaning of the different values in the `summary.txt` are explained in section.




=== Directory `fmus`

Inside this directory, the imported FMUs are extracted, each in a subdirectory with basename of the FMU (`part1.fmu` -> `part1`).

When a _MasterSim_ project references several FMUs with same base name, which are for example in different subdirectories, then it will adjust the extraction path name. Example:

[source,python]
------
slave1 : /path/to/fmus/s1.fmu
slave2 : /path/to/fmus/s1.fmu                # <1>
slave3 : /path/other/project/fmus/s1.fmu     # <2>

# _MasterSim_ generates directories
.../fmus/s1
.../fmus/s1_2                                # <3> 
------
<1> second instance of same FMU
<2> different FMU with same basename
<3> suffix 2 and 3 etc. is added by _MasterSim_

Basically, each 'fmu' file is only extracted once.
[TIP]
====
.Skipping the FMU extraction step
MasterSim provides the command line option `--skip-unzip`, that is very useful for fixing FMUs with errors in the `modelDescription.xml` or missing resources. If such an FMU is encountered, you can ran MasterSimulator once to extract the FMUs into the directory, then edit/adjust the bad files in the respective extraction directory and afterwards run the simulation again with `--skip-unzip`. _MasterSim_ will now directly read the (modified) files and you can save yourself the hassle of zipping and renaming the FMU. Also, you can keep the `modelDescription.xml` opened in the editor and quickly iterate through the edit-and-test-run procedure, until everything works.

See also section <<_modifyingfixing_fmu_content,Modifying/fixing FMU content>>.
====


=== Directory `slaves`

Often, non-trivial simulation slaves write their own output files, instead of pushing all output data via FMI output variables to the master. In cases, where PDEs are solved and many thousands of variables are generated, this may actually not be possible.

Since a slave FMU may be instantiated several times, hard-coding output paths inside the FMU is generally a bad idea (though still current practice). Also, writing outputs into the current working directory is not too smart either, since the working directory would have to be changed by the master between calls to FMUs, and this is best avoided.

Unfortunately, the FMU standard does not provide an option, to officially set such a result directory. _MasterSim_ handles this by setting the slave-specific directory path in a string parameter named *ResultsRootDir*, if the FMU declares such a parameter. If there is no value set in the project file for this parameter, then _MasterSim_ will set the path generated for the slave in the working directory. The FMU can rely on the path being created by _MasterSim_ and being writable.  
Of course, as with any parameter, you can set manually a value for this parameter.


== Simulation output

=== Slave output values

_MasterSim_ creates two result files within the `results` subdirectory.

`values.csv`:: Number outputs of all output variables of all slaves (whether they are connected or not).
`strings.csv`:: Values of all output variables of type string of all slaves.

and depending on whether _synonymous variables_ are defined in the ModelDescription (see below), the file `synonymous_variables.txt`.

String output files are only generated when outputs of this type are generated. CSV files use tab chars as separators. First column is always the time point, the column header indicates the time unit.

Example `values.csv` file:

----
Time [s] 	slave1.h [-] 	slave1.v [-]
0	1	0
0.001	0.999995099905	-0.0098100000000001
0.0019999999999999	0.99998038981	-0.019619999999999
0.0030000000000001	0.999955869715	-0.029430000000002
0.0040000000000002	0.99992153962	-0.039240000000001
----

The file format corresponds to that of the csv-files used as FileReader-slaves, see section <<_csv_filereader_slaves,CSV FileReader Slaves>>, with:

- tabulator separated columns,
- numbers written in english number format, and
- a single header line identifying the variables.

The FMI variable names are prefixed with the corresponding slave name. The units are given in brackets and for unitless integer and boolean data types, the unit [-] is used.

==== Synonymous variables

Some FMUs (i.e. those generated from Modelica models) may have several (internal) variables that share the same value reference. This happens, when the symbolic analysis of the Modelica model has identified those variables as the same. In this case, MasterSim does not write duplicate output variables (would be a waste of harddrive space and simulation time, see ticket #47), but instead create a file `synonymous_variables.txt` with a table of synonymous variables.

The table is written as plain text file with tab-separated columns:

1. fmu filename (currently, only the file name is written  - in case that the _same filename_ with _different file paths_ is being used, this may need to be changed)
2. the name of the variable that appears in the `values.csv` file
3. the synonymous variable, that is not written into the output file, since it has the same value anyway

Example for `synonymous_variables.txt` file:

----
ControlledTemperature.fmu	heatCapacitor.T	heatCapacitor.port.T
ControlledTemperature.fmu	heatCapacitor.T	heatingResistor.T_heatPort
ControlledTemperature.fmu	heatCapacitor.T	heatingResistor.heatPort.T
ControlledTemperature.fmu	heatCapacitor.T	temperatureSensor.port.T
ControlledTemperature.fmu	heatCapacitor.T	thermalConductor.port_a.T
ControlledTemperature.fmu	heatingResistor.p.v	heatingResistor.v
ControlledTemperature.fmu	heatingResistor.p.v	idealSwitch.n.v
ControlledTemperature.fmu	constantVoltage.i	constantVoltage.n.i
ControlledTemperature.fmu	constantVoltage.i	constantVoltage.p.i
ControlledTemperature.fmu	constantVoltage.i	heatingResistor.i
ControlledTemperature.fmu	constantVoltage.i	heatingResistor.n.i
ControlledTemperature.fmu	constantVoltage.i	heatingResistor.p.i
ControlledTemperature.fmu	constantVoltage.i	idealSwitch.i
ControlledTemperature.fmu	constantVoltage.i	idealSwitch.n.i
ControlledTemperature.fmu	constantVoltage.i	idealSwitch.p.i
ControlledTemperature.fmu	heatingResistor.LossPower	heatingResistor.heatPort.Q_flow
ControlledTemperature.fmu	fixedTemperature.port.Q_flow	thermalConductor.Q_flow
ControlledTemperature.fmu	fixedTemperature.port.Q_flow	thermalConductor.port_a.Q_flow
ControlledTemperature.fmu	fixedTemperature.port.Q_flow	thermalConductor.port_b.Q_flow
ControlledTemperature.fmu	onOffController.reference	ramp.y
ControlledTemperature.fmu	onOffController.u	temperatureSensor.T
ControlledTemperature.fmu	idealSwitch.control	logicalNot.y
ControlledTemperature.fmu	logicalNot.u	onOffController.y
----


=== Final statistics/summary

_MasterSim_ contains internal profiling functions that monitor the evaluation times of various parts of the software. Also, execution counts for different critical functions are shown.

The statistics is printed on the console window (for verbosity level > 0) and in the log file `screenlog.txt` in the following format:

------
Solver statistics
------------------------------------------------------------------------------
Wall clock time                            =   78.044 ms  
------------------------------------------------------------------------------
Output writing                             =   76.767 ms  
Master-Algorithm                           =    0.666 ms         324
Convergence failures                       =                      41
Convergence iteration limit exceeded       =                      41
Error test time and failure count          =    0.214 ms          85
------------------------------------------------------------------------------
Part1                               doStep =    0.101 ms        1229
                                  getState =    0.070 ms        1116
                                  setState =    0.020 ms         509
Part2                               doStep =    0.079 ms        1496
                                  getState =    0.039 ms        1116
                                  setState =    0.024 ms         776
Part3                               doStep =    0.071 ms        1496
                                  getState =    0.038 ms        1116
                                  setState =    0.040 ms         776
------------------------------------------------------------------------------
------

Also, the same statistics information is printed into the `summary.txt` log file, in a more _machine-friendly_ format (with timings always in *seconds*):

------
WallClockTime=0.078044
FrameworkTimeWriteOutputs=0.076767
MasterAlgorithmSteps=324
MasterAlgorithmTime=0.000666
ConvergenceFails=41
ConvergenceIterLimitExceeded=41
ErrorTestFails=85
ErrorTestTime=0.000214
Slave[1]Time=0.000191
Slave[2]Time=0.000142
Slave[3]Time=0.000149
------


Wall clock time:: total simulation time spend after initialization. Time for unzipping and loading of shared libraries is excluded (`WallClockTime`).

Output writing:: time spent in writing output files and computing values related to such outputs (`FrameworkTimeWriteOutputs`)

Master-Algorithm:: Time spent in the actual master algorithm (`MasterAlgorithmTime`) and number of calls to the algorithm and overall time steps taken (`MasterAlgorithmSteps`)

Convergence failures:: Number of times an iterative master algorithm failed to converge within the allowed number of iterations or diverged. Only applies to iterative master algorithms (`ConvergenceFails`)

Convergence iteration limit exceeded:: Number of times an iterative master algorithm failed to converge within the allowed number of iterations (should be less or equal to convergence failure count). Only applies to iterative master algorithms (`ConvergenceIterLimitExceeded`)

Error test time and failure count:: Number of times the error test failed (`ErrorTestFails`) and overall time needed for performing error tests, including the time for resetting FMU states and re-evaluating steps (`ErrorTestTime`). Only applies to master algorithms with enabled error control (Richardson-variants).

The remaining lines show timings and counters for each slave individually.  This lines show the time taken in the function calls to `doStep()`, `getState()` and `setState()` for this slave and the respective call count. The state-related functions are only used by iterative master algorithms, when the FMUs support FMI 2.0 features. Mind, these functions are called both by the master algoritm and by the error test (if enabled).

*Output writing* and *Master-Algorithm* are the major two components of the MasterSimulator program, so there times should sum up close to the total wall clock time.

The third column in the screenlog-statistics contains counters. The counter for Master-Algorithm is the number of times the master algorithm takes a step, so that's the total step count. Re-tries and iterations _within_ the master algorithm are not counted here.

The last section of the statistics lists timings and counters for individual FMU slaves and the most relevant functions.

[TIP]
====
You may use these profiling values to tune your simulation and identify, in case of very slow simulations, which of the FMUs is taking up most of the time. Also, it helps identifying if one of the fast functions (get and set state) are taking way too much time.
====

---