name: Ubuntu 20.04 build and tests

on:
  # run nightly at 2:00 am
  schedule:
    - cron: "0 2 * * *"
  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    # Test suite results are created on Ubuntu 20.04, hence we need to use this for testing
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: build
      working-directory: build/cmake
      run: ./build.sh 2 release
