name: Windows VC2019 x64

on:
  # run nightly at 4:00 am
#  schedule:
#    - cron: "0 4 * * *"
  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: install jom
      run: choco install jom -y
    - name: install qt5
      uses: jurplel/install-qt-action@v4
      with:
        host: 'windows'
        target: 'desktop'
        install-deps: 'true'
        arch: win64_msvc2019_64
        archives: 'qtbase qtsvg'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
    - uses: actions/checkout@v4
    - name: build
      working-directory: build/cmake
      shell: cmd
      run: build_VC_x64.bat
